version: '2'
services:
  sampleneo4jnocache-app:
    image: sampleneo4jnocache
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  sampleneo4jnocache-neo4j:
    extends:
      file: neo4j.yml
      service: sampleneo4jnocache-neo4j
